import { GithubUser } from '../../../shared';

export const githubApi: GithubUser[] = [
  {
    login: 'DeveloperParana',
    id: 15199454,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjE1MTk5NDU0',
    avatar_url: 'https://avatars.githubusercontent.com/u/15199454?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DeveloperParana',
    html_url: 'https://github.com/DeveloperParana',
    followers_url: 'https://api.github.com/users/DeveloperParana/followers',
    following_url:
      'https://api.github.com/users/DeveloperParana/following{/other_user}',
    gists_url: 'https://api.github.com/users/DeveloperParana/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DeveloperParana/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DeveloperParana/subscriptions',
    organizations_url: 'https://api.github.com/users/DeveloperParana/orgs',
    repos_url: 'https://api.github.com/users/DeveloperParana/repos',
    events_url: 'https://api.github.com/users/DeveloperParana/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DeveloperParana/received_events',
    type: 'Organization',
    site_admin: false,
    name: 'DevParaná',
    company: null,
    blog: 'https://devparana.org',
    location: null,
    email: 'contato@devparana.org',
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 24,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: '2015-10-19T16:21:51Z',
    updated_at: '2020-07-12T00:54:13Z',
  },
  {
    login: 'guiseek',
    id: 5638096,
    node_id: 'MDQ6VXNlcjU2MzgwOTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5638096?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/guiseek',
    html_url: 'https://github.com/guiseek',
    followers_url: 'https://api.github.com/users/guiseek/followers',
    following_url:
      'https://api.github.com/users/guiseek/following{/other_user}',
    gists_url: 'https://api.github.com/users/guiseek/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/guiseek/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/guiseek/subscriptions',
    organizations_url: 'https://api.github.com/users/guiseek/orgs',
    repos_url: 'https://api.github.com/users/guiseek/repos',
    events_url: 'https://api.github.com/users/guiseek/events{/privacy}',
    received_events_url: 'https://api.github.com/users/guiseek/received_events',
    type: 'User',
    site_admin: false,
    name: 'Guilherme Siquinelli',
    company:
      '@BeTrybe, @DeveloperParana, @hacktoberfest-brasil, @eventos-do-bem, @GUMGA, @Serrabits',
    blog: 'https://guiseek.dev',
    location: 'Maringá, Paraná',
    email: null,
    hireable: null,
    bio: 'Engenheiro Web e degustador de novas tecnologias.\r\n',
    twitter_username: 'guiseek',
    public_repos: 255,
    public_gists: 32,
    followers: 167,
    following: 109,
    created_at: '2013-10-08T12:40:15Z',
    updated_at: '2022-07-20T13:57:14Z',
  },
];
